apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: pulsar-consumer
        image: abhisaini/pulsar_consumer
        ports:
        - containerPort: 80
