apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: pulsar-producer
        image: abhisaini/pulsar_producer
        ports:
        - containerPort: 80
